### ISSUE TITLE
Compass -> Ring of Light mě hodil na prázdnou stránku

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#100]
Koupil jsem Ring of Light a ocitnul jsem se na prázdné stránce
<img width="1428" alt="Screenshot 2020-05-09 at 22 36 17" src="https://user-images.githubusercontent.com/64065488/81484414-8598be00-9245-11ea-9374-e46aeac5b5ae.png">

**Comment by faire2** [comment]
Výroční issue #100!

**Comment by faire2** [comment]
Přepsáno na modál:
![image](https://user-images.githubusercontent.com/45813901/81495466-bbbf5780-92b0-11ea-8477-3882cdaa9526.png)
