### ISSUE TITLE
Lokace Defeat a Guardian - nefunguje na Guardiany v Discard pile

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#101]
<img width="1255" alt="Screenshot 2020-05-09 at 22 42 39" src="https://user-images.githubusercontent.com/64065488/81484552-79f9c700-9246-11ea-97be-9f1ffd2c06d2.png">

**Comment by ElwenCGE** [comment]
BTW. v rámci updatu z této lokality můžeš odstanit ten zlaťák co k tomu dává - porazit Guardiana je dostatečně silné

**Comment by ElwenCGE** [comment]
ale pěkně u toho fungovalo "cancel effekt" a nezasekl jsem se díky tomu :)

**Comment by faire2** [comment]
Opraveno, lokace upravena.
