### ISSUE TITLE
Destroy a card (a i draw a card) budou optional

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#104]
Začal bych implementací Destroy a card. Ta možnost je volitelná, takže by tam měla být možnost kliknout na tlačítko (skip effect) nebo něco takového.

Stejně byla zamýšlená možnost u Draw a card.

**Comment by ElwenCGE** [comment]
Nicméně (skip effect) by nefungoval dobře u Draw a card. Aby se to sjednotilo (destoy / draw) tak by ten dialog měl mít potvrzení ve smyslu tlačítka Use effect.
Nechám si v tomto poradit, jaká forma by podle tebe byla nejpříjemnější na používání.

**Comment by faire2** [comment]
Teď už je tam implementováno tlačítko právě pro zrušení destroy efektu - co by se k tomu mělo ještě dodělat?

Tlačítko se objeví jen u destroy efektů (znič kartu, poraž guardiana).
