### ISSUE TITLE
Špatný asistent v místě zlatého je stříbrný (tablet)

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#107]
<img width="621" alt="Screenshot 2020-05-10 at 14 42 23" src="https://user-images.githubusercontent.com/64065488/81499524-8f193900-92cc-11ea-90a6-db9909819a11.png">

Dokonce když jsem poslední zlatý sebral, tak tam zbyly 2 stříbrné (tablet)
<img width="440" alt="Screenshot 2020-05-10 at 14 46 19" src="https://user-images.githubusercontent.com/64065488/81499627-2f6f5d80-92cd-11ea-80b6-3e868b81f7a0.png">

**Comment by faire2** [comment]
Opraveno.
