### ISSUE TITLE
Grappling Hook - při výběru J v sousední lokalitě vše zmizelo, zbyla prázdná obrazovka

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#110]
...mohlo by to být i tím, že partie byla dlouho rozehraná, ale před zahráním Grappling hooku jsem ještě úspěšně poslal panáčka na lokalitu, tak nevím.

**Comment by Minmyska** [comment]
Taky se mi stalo. Kliknutí na základní JE lokalitu.


![Grappling_Hook](https://user-images.githubusercontent.com/30267393/81851164-52ae3d00-9559-11ea-80ea-117670046124.JPG)

**Comment by faire2** [comment]
Díky za přiložení screenu z konzole! 
Zkoušel jsem teď základní lokalitu 4x z vedlejší lokality a 1x z jiné řady, vždy fungovala korektně.

Nezáleží na tom, v které je pozici? U mě to byla 1. lokalita v 1. řadě...
