### ISSUE TITLE
Nemůžu kliknout na lokalitu, i když mám panáčka a dopravní prostředek

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#112]
zachránil jsem panáčka od guardiana,
pak jsem zahrál jeep, ale nejsem schopný kliknout na jeepovou lokalitu

<img width="849" alt="Screenshot 2020-05-13 at 07 50 53" src="https://user-images.githubusercontent.com/64065488/81776175-a6d00780-94ee-11ea-865d-b575d00b9965.png">

**Comment by faire2** [comment]
Nepodařilo se mi to reprodukovat, možná to souvisí s tím vraceným adventurerem. 
Budu potřebovat to logování rozšířit i na tyhle věci :).

**Comment by ElwenCGE** [comment]
Repro na stejné pozici, tentokrát mi nic panáčka nevracelo
<img width="904" alt="Screenshot 2020-05-13 at 15 08 48" src="https://user-images.githubusercontent.com/64065488/81816530-b9b4fd00-952b-11ea-8f62-73c81123b72e.png">

**Comment by ElwenCGE** [comment]
<img width="574" alt="Screenshot 2020-05-13 at 15 12 05" src="https://user-images.githubusercontent.com/64065488/81817278-ca19a780-952c-11ea-879d-0a9b5d4563dc.png">
Ta lokalita vyžadovala 2 jeeps. Fixnul jsem to

**Comment by faire2** [comment]
https://i.imgur.com/Kah4ASE.gif?noredirect
