### ISSUE TITLE
Compass - pokud něco přeruší efekt, tak nabídka karet zůstane rozšířená o +1 kartu

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#113]
<img width="761" alt="Screenshot 2020-05-13 at 07 54 53" src="https://user-images.githubusercontent.com/64065488/81776530-4097b480-94ef-11ea-9977-57f4b2d7e201.png">

**Comment by faire2** [comment]
Cancel effect, nebo něco jiného?
