### ISSUE TITLE
Aktivace (i automatická) zlatého asistenta crashne hru (bílá obrazovka)

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#119]

**Comment by faire2** [comment]
Myslím si, že ta chyba souvisela se špatným nastavením dobírání asistentů, zvl. zlatých. Opravil jsem ji, jednotlivé asistenty jsem při tom několikrát použil bez pádu. Hra padala pouze tehdy, když už neměla další asistenty na zobrazení (a pak se do ní nedalo ani vrátit). IMHO by mělo být opraveno.
