### ISSUE TITLE
2h Hard Undo

### ISSUE THREAD

**Issue by faire2** [faire2/loreHunters#124]

**Comment by faire2** [comment]
@ElwenCGE Je tam jeden problém - soft undo řeší všechny situace kromě těch, kdy skončil tah. Konec tahu ale přenese iniciativu dalšímu hráči, který může mezitím začít hrát. Má se to udělat tak, že prostě můžeš vzít zpátky iniciativu a vrátit se k začátku svého tahu, nebo jinak?

**Comment by ElwenCGE** [comment]
Ano, to je jak to bylo zamýšleno. Oni ti lidi většinou budou ve spojení, takže ta situace se bude vyvíjet "jejda, to jsem nechtěl, nevadí když to vezmu zpátky?" - tak jak to je někdy u stolu

**Comment by faire2** [comment]
ok, chtěl jsem si to ověřit
basic implementace je teda bez zdvořilé prosby :)
