### ISSUE TITLE
Guardian mají -1VP i když jsou poražení, místo toho aby zobrazovali svou hodnotu

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#14]
<img width="429" alt="Screenshot 2020-04-23 at 08 08 33" src="https://user-images.githubusercontent.com/64065488/80065041-be445200-8539-11ea-87b1-58fb413b3ed4.png">

**Comment by ElwenCGE** [comment]
Tak možná se to týká jen Whispering Shadow, Golem normálně zobrazuje 2VP

**Comment by faire2** [comment]
Jj, chyba v hodnotě, opravím s updatem.
