### ISSUE TITLE
•	Scoring, undo, revert bych nechal vedle ostatních tlačítek (end of round, plane)

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#141]

**Comment by faire2** [comment]
On se tam zobrazuje popis aktuálního efektu - kam s ním? Je to spojené s celkovým layoutem.

**Comment by faire2** [comment]
Hotovo, text jsem zatim nechal na miste, kdyz tak shiftneme se zmenou layoutu
