### ISSUE TITLE
(important) Když se vyleveluje asistent, tak i když byl použitý má být opět ready.

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#145]

**Comment by ElwenCGE** [comment]
Z asistenta [E] / Ship se stal [Plane] [C] - to není správně. Zkusím to updatnout jestli je chyba v tabulce, ale možná je to bug.

**Comment by faire2** [comment]
Zbytek asistentů fungoval? Já je ještě nemám v hlavě, ale přišlo mi, že mi to dává smysluplný upgrade..
