### ISSUE TITLE
Nové fungování Lost City

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#147]
Poslední políčko v Lost City dává Exile card efekt jinak nic (ne třetinu bonusu)

V lost city hráč získává už jen body - žádné výhody z relicků. 3b za bronzovou, 7b za stříbrnou, 11b za zlatou

**Comment by faire2** [comment]
@ElwenCGE Takže ve hře zůstávají jen efekty na relikviích získaných za objevení lokací?
Nové body za relikvie platí pro celou hru, tj. i pro relikvie získané v lokacích?
