### ISSUE TITLE
sleva 2 na artefact nebo item / nikoliv 1+1

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#152]
<img width="54" alt="Screenshot 2020-08-19 at 22 58 39" src="https://user-images.githubusercontent.com/64065488/90688975-95299900-e26f-11ea-9329-b94b75324c21.png">
toto je sleva 2 na artefact nebo item

**Comment by ElwenCGE** [comment]
ještě neopraveno - zatím jsem to přepsal na jiný efekt - celkově bychom měli mít 12 asistentů

**Comment by faire2** [comment]
Opraveno, efekt buyWithDiscount2, nestiham testovat, ale vypada bezpecne. U asistenta si to prosim prehod zpatky sam, tech zmen je tam vice.

**Comment by faire2** [comment]
@ElwenCGE
