### ISSUE TITLE
Uptrade dialog

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#17]
Přesunul jsem se na legendě na uptrade, hra mi nedá nijak najevo, co mám dělat dál (ani textově. Nicméně kliknutí na zdroj skutečně provede uptrade.) Spíš by to mělo být v nějaké vyskakovacím okně.
<img width="1902" alt="Screenshot 2020-04-23 at 08 21 05" src="https://user-images.githubusercontent.com/64065488/80066074-8c33ef80-853b-11ea-8640-35c975dcdbe4.png">

**Comment by faire2** [comment]
Jo, muzeme to dat do modalu, zatim se zobrazuje alespon aktivni efekt:

![image](https://user-images.githubusercontent.com/45813901/80111188-dd65d280-857f-11ea-9af5-96e1171391a3.png)
