### ISSUE TITLE
přetékající karty blokují suroviny

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#19]
<img width="1249" alt="Screenshot 2020-04-23 at 08 27 38" src="https://user-images.githubusercontent.com/64065488/80066528-61966680-853c-11ea-8508-47a3eba42a39.png">

**Comment by faire2** [comment]
![image](https://user-images.githubusercontent.com/45813901/80198038-d1c9e880-861f-11ea-943e-e2423f11dd9f.png)
