### ISSUE TITLE
feature request: income tiles, aktivace všech na kliknutí

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#20]
<img width="192" alt="Screenshot 2020-04-23 at 08 29 17" src="https://user-images.githubusercontent.com/64065488/80066656-a15d4e00-853c-11ea-881f-455451456676.png">

aktuálně se na tyto dílky dá kliknout, ty se otočí, ale nic neudělají, protože už daly income na začátku kola.
To je docela matoucí, asi bych to sjednotil, že se income tiles (všechny) aktivují jako free akce až po kliknutí.

**Comment by faire2** [comment]
Nebo se mohou rovnou zobrazovat jako kliknuté, ať to ulehčí hráčům?
