### ISSUE TITLE
Nekončící hra

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#21]
Hra se po pátém kole neukončí, přejde do šestého soudě podle artefaktů.
Mám tam podezření na konci na vícero bugů - dost možná spojených s příchodem všech guardianů atd. Ještě to budu muset prozkoumat. 
<img width="838" alt="Screenshot 2020-04-23 at 08 35 14" src="https://user-images.githubusercontent.com/64065488/80067393-06fe0a00-853e-11ea-9fdb-045d5f8042db.png">

**Comment by faire2** [comment]
Po konci pátého kola hra automaticky přesměruje na Scoring board, nevím, jestli se budou perfektně zobrazovat data, to chce otestovat - zvláště při hře více hráčů.
