### ISSUE TITLE
bug - boomerang

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#25]
<img width="1793" alt="Screenshot 2020-04-27 at 11 26 08" src="https://user-images.githubusercontent.com/64065488/80356663-0cc75880-887a-11ea-86ba-02592067dfb4.png">
<img width="1863" alt="Screenshot 2020-04-27 at 11 26 22" src="https://user-images.githubusercontent.com/64065488/80356674-10f37600-887a-11ea-90d3-da91c4a67110.png">
<img width="1840" alt="Screenshot 2020-04-27 at 11 26 31" src="https://user-images.githubusercontent.com/64065488/80356683-1486fd00-887a-11ea-91d0-6f18da735b76.png">

**Comment by ElwenCGE** [comment]
1) zahrál jsem boomerang, získal správně C a E a dobral si džíp, hra říká ať discardnu karty
2) kliknu na jeep 
- přibude mi E (??)
- objeví se Coin card (???)
- stále je tam dialog ať discardnu kartu
3)kliknu na tu Coin card 
- zmízí mi zbraň (??????)
- a dál to po mně chce abych něco discardnul

**Comment by ElwenCGE** [comment]
boomerang jsem získal tak, že jsem relic dal na místo dober kartu

**Comment by faire2** [comment]
Mel by fungovat.
