### ISSUE TITLE
Owl's eyes nefungují

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#30]
koupil jsem owl's eyes - objevili se v discardu (je to artefakt, měly by jít do paly area) a současně zůstaly i v nabídce marketu.
Žádné resources jsem nedostal (neobjevila se nabídka guardianů)
<img width="530" alt="Screenshot 2020-04-28 at 09 52 07" src="https://user-images.githubusercontent.com/64065488/80461850-30e86f80-8936-11ea-83f2-5c86078f3e57.png">

**Comment by faire2** [comment]
Opraveno a současně OE vyhozeny z momentálně aktivních karet.
