### ISSUE TITLE
Lokalita, kde se platí karta za zdroje, nefunguje

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#32]
poslal jsem panáčka jeepem na lokalitu, kde je třeba zahodit kartu, abych něco dostal.
- hra mě dialogem nevybínula, abych zahodil kartu
- karta šla discardnout, ALE nedostal jsem za to žádné resources

<img width="1134" alt="Screenshot 2020-04-28 at 09 57 01" src="https://user-images.githubusercontent.com/64065488/80462366-e3b8cd80-8936-11ea-9eb0-8a8b045247bd.png">

**Comment by faire2** [comment]
Pokračování včerejšího problému s discardy, jen na jiném místě :) Opraveno.

**Comment by ElwenCGE** [comment]
Stále se to děje.

**Comment by ElwenCGE** [comment]
Repro se mi povedlo vícekrát:

<img width="1380" alt="Screenshot 2020-05-03 at 20 31 13" src="https://user-images.githubusercontent.com/64065488/80922420-51bd2480-8d7d-11ea-89cf-c450c4fb9ce8.png">
kliknu na vrchní bonus a další obrazovka je tato:
<img width="1338" alt="Screenshot 2020-05-03 at 20 31 20" src="https://user-images.githubusercontent.com/64065488/80922426-5bdf2300-8d7d-11ea-8809-d6c5307d7bda.png">
mám normální další akci, kliknutí na kartu ji normálně zahraje, nediscarduje

**Comment by ElwenCGE** [comment]
potvrzeno v multiplayru
