### ISSUE TITLE
poslední zlatá akce poráží guardiana (namísto přidávání panáčka)

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#33]
<img width="131" alt="Screenshot 2020-04-28 at 10 01 00" src="https://user-images.githubusercontent.com/64065488/80462628-44480a80-8937-11ea-9e57-057566c9dfbb.png">

**Comment by faire2** [comment]
Tohle se mi nepodařilo reprodukovat, jestli na to ještě narazíš, dej vědět.
