### ISSUE TITLE
Mezi skórovanými předměty jsou i neporažení Guardiani (ti co zůstali v discardu)

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#35]
<img width="1317" alt="Screenshot 2020-04-29 at 12 35 36" src="https://user-images.githubusercontent.com/64065488/80586993-1ab1e080-8a16-11ea-977a-8f7fb92322d1.png">

**Comment by faire2** [comment]
Pocitalo se spravne, ale zobrazovaly se tam i karty, ktere tam byt nemely. Opraveno.
