### ISSUE TITLE
První přihlášení - chybí tlačítko

### ISSUE THREAD

**Issue by Minmyska** [faire2/loreHunters#40]
Po napsání jména enter nic neudělá. Je potřeba kliknout mimo textové pole, aby se dalo pokračovat.

**Comment by faire2** [comment]
![image](https://user-images.githubusercontent.com/45813901/80703400-ff60d700-8ae2-11ea-9450-5473875a611f.png)

Spravím.

**Comment by faire2** [comment]
Textové pole už reaguje i na enter.
