### ISSUE TITLE
Chyba po vyřešení Guardiana

### ISSUE THREAD

**Issue by Minmyska** [faire2/loreHunters#44]
Po zahrání Guardiana se u druhého hráče objeví bílá obrazovka a tahle chybová hláška:

![Guardian](https://user-images.githubusercontent.com/30267393/80706292-5d43ed80-8ae8-11ea-9c58-b7253f088270.JPG)

**Comment by faire2** [comment]
Souvisi se zobrazovanim zdroju protihracu.

**Comment by faire2** [comment]
Nejspíše opraveno, ověřeno ve hře dvou hráčů.
