### ISSUE TITLE
Koupený artefact (Dark Knowledge) po koupi šel do discardu na místo do play area a někde se objevil navíc Guardian (?)

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#46]
<img width="401" alt="Screenshot 2020-05-01 at 06 52 18" src="https://user-images.githubusercontent.com/64065488/80782995-975cd000-8b78-11ea-8455-34a7a05b2168.png">

**Comment by faire2** [comment]
Artefakty šly do discardu, to jsem opravil.
Dark Knowledge měl nastaveno, že je guarded, to jsem opravil.
Artefakty nezobrazovaly, zda jsou guarded, to jsem opravil.

![image](https://user-images.githubusercontent.com/45813901/80786769-e6a8fd80-8b84-11ea-8bda-11d63bad68f4.png)
