### ISSUE TITLE
Po refresh hry a návratu na stránku hry nelze pokračovat ve hře (kliknutí na Open nic nedělá)

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#47]
<img width="570" alt="Screenshot 2020-05-01 at 06 55 22" src="https://user-images.githubusercontent.com/64065488/80783083-d3903080-8b78-11ea-8ebd-a9d975de59b8.png">

**Comment by ElwenCGE** [comment]
Dále založené hry již nemají tlačítko Open - tak jsem asi dotestoval ;)
<img width="655" alt="Screenshot 2020-05-01 at 06 57 05" src="https://user-images.githubusercontent.com/64065488/80783160-118d5480-8b79-11ea-91bf-762503fff3dc.png">

**Comment by ElwenCGE** [comment]
Feature Request: mít možnost smazat místnost

**Comment by ElwenCGE** [comment]
Po otevření druhého prohlížeče Chrome s jiným Nickem. Ty nově založené hry se založily tam, místo aby byly u Elwena (ojoj :) )
<img width="554" alt="Screenshot 2020-05-01 at 06 59 09" src="https://user-images.githubusercontent.com/64065488/80783259-721c9180-8b79-11ea-8d5f-e21d488846a7.png">

**Comment by faire2** [comment]
To, co se stalo, bylo odpojení klienta. Další založené místnosti se "nazásobníkovaly" a v okamžiku připojení se teprve vytvořily, a to u připojeného klienta. 

Udělal jsem teď v síťovém kódu dost změn, mohl bys to ještě jednou projet? Část problémů by už měla být vyřešená.

Zbývá ještě dodělat tlačítko na mazání místností a zabránit ve vytvoření místností, pokud je uživatel offline.
