### ISSUE TITLE
Nefunguje správně Mirror Shard

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#48]
Koupil jsem mirror shard.
Nesprávně se okamžitě doplnil nový artefakt (měl by se doplnit až po dokončení efektu karty, ale kdyby to byl problém, tak na to kašli, tohle není důležité, spousta jiných bugů ano :)).

Nicméně po koupi mirror shardu on stále zůstal v nabídce, která se tak rozrostla na 7 karet

<img width="1494" alt="Screenshot 2020-05-01 at 08 42 16" src="https://user-images.githubusercontent.com/64065488/80787825-de05f680-8b87-11ea-9a74-bb79389fac7c.png">

**Comment by faire2** [comment]
Právě jsem to opravil, je to v dalším pushi. 
Doplňování jsem si všimnul, můžeme to nechat na později.
