### ISSUE TITLE
Na začátku 5. kola Guardians zůstali v balíku

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#49]
Právě začalo 5. kolo, Energy Leech je v mém dobíracím balíku
<img width="872" alt="Screenshot 2020-05-01 at 08 46 40" src="https://user-images.githubusercontent.com/64065488/80788046-6d130e80-8b88-11ea-81c3-79314172fa6f.png">

(tohle je ve stejné hře co nesprávně fungoval mirror shard, tak nevím jestli to třeba nemohlo být i tím)

**Comment by ElwenCGE** [comment]
Stejně tak po koupi artefaktu co dává guardiana tento zůstal v discardu:
<img width="671" alt="Screenshot 2020-05-01 at 08 55 38" src="https://user-images.githubusercontent.com/64065488/80788514-a1d39580-8b89-11ea-9795-b343eee544fd.png">

**Comment by faire2** [comment]
Po koupi artefaktu to nefungovalo, stejne jako pri jejich ziskani pres aktivni efekt - oboji jsem opravil.
