### ISSUE TITLE
nepřibyl mi Explore za posun v legendě

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#51]
<img width="262" alt="Screenshot 2020-05-01 at 11 17 13" src="https://user-images.githubusercontent.com/64065488/80795681-7490e280-8b9d-11ea-8db1-54a138760cf0.png">
zaplatil jsem minci a 3x text za posun ve spodním řádku, nepřibyl mi explore

**Comment by faire2** [comment]
Pribyla Ti Coin :)

Opraveno.
