### ISSUE TITLE
Flask je zabugovaná

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#52]
Zahrál jsem Flask, vrátila se mi do discardu - v dalších kolech se dala zahrát dokonce vícenásobně

<img width="858" alt="Screenshot 2020-05-01 at 11 22 08" src="https://user-images.githubusercontent.com/64065488/80795898-1e706f00-8b9e-11ea-996f-76e11f171392.png">

**Comment by faire2** [comment]
Opraveno
