### ISSUE TITLE
Dog (Pigeon?) nefunguje

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#53]
<img width="628" alt="Screenshot 2020-05-01 at 20 36 29" src="https://user-images.githubusercontent.com/64065488/80831675-8d27e980-8beb-11ea-9af2-53fc1aac2a69.png">

holubem jsem si dobral do ruky psa. Pak jsem zahrál psa a nic jsem nedobral i když mám 4 karty v draw decku

**Comment by faire2** [comment]
IMHO byl problem v tom, ze se zahral pidgeon jako discard, proto to vypadalo, ze nic nedela.
