### ISSUE TITLE
III lokalita (discard card -> TTWW) nefunguje při objevení

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#54]
<img width="644" alt="Screenshot 2020-05-01 at 20 41 32" src="https://user-images.githubusercontent.com/64065488/80832043-3b339380-8bec-11ea-9050-cfbbce965eb5.png">

Objevil jsem lokalitu nahoře, zvolil možnost zahodit zbývající kartu a vzít TTWW, ale neobjevil se dialog na zahození karty a já nic nedostal

**Comment by ElwenCGE** [comment]
při běžném hraní funguje v pořádku, takže je to možná jen při tom objevení nové lokace

**Comment by faire2** [comment]
Bylo to opravdu vazano na objeveni lokace, melo by fungovat (problem byl v tom, ze kolo skoncilo jeste pri otevrenem okne s odmenami, a vybrana odmena se pak uz nezapsala, tedy ani jeji discard efekt).
