### ISSUE TITLE
hot air baloon nefunguje - neklikatelny

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#57]

**Comment by ElwenCGE** [comment]
tak je klikatelny, velke mnozstvi karet laguje hru... ale funguje nespravne, neobjevi lokalitu, da ti EE ?

**Comment by ElwenCGE** [comment]
tak je někdy klikatelný, viz podivnost bug

**Comment by faire2** [comment]
Efekt opraven, ale bude to jeste chtit otestovat.
