### ISSUE TITLE
Active effects / cards with transports cannot be played

### ISSUE THREAD

**Issue by faire2** [faire2/loreHunters#6]
When a card giving transport as a part of its effect is played, turn ends and transport cannot be used (Ostrich). Same problem is expected with active effects.

**Comment by ElwenCGE** [comment]
Cards that generates extra action

- items
Ostrich
Turtle

- artifacts
Flaming jewel
Inscribed blade

- kapitola sama o sobě
Mirror shard

**Comment by faire2** [comment]
Asi to funguje, za Mirror shard nerucim, ale zkousel jsem ho uspesne :)
