### ISSUE TITLE
Bug: Portal stone - zmizí panáčka

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#63]
repro: zahrej 1. panáčka na nějakou lokalitu, zahraj portal stone, odstraň panáčka (zmizí ti i druhý ze zásoby), zůstane ti potom jen jeden

**Comment by faire2** [comment]
Opraveno.

**Comment by ElwenCGE** [comment]
Tak opět se děje tato chyba

**Comment by ElwenCGE** [comment]
bump, pokud by byl fix delší, tak stačí zatím portal stone zakomentovat

**Comment by faire2** [comment]
Opraveno podruhé. Z nějakého důvodu jsem měl za potřebné odstranit dobrodruha ze zdrojů, ale asi to není potřeba, takže jsem to zrušil. Předmět funguje s jedním i dvěma nasazenými dobrodruhy.
