### ISSUE TITLE
Zahráni Journalu mi přidalu méně Exploru než mělo

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#65]
Přidalo mi to jen E namísto EEE, asi to počítí jen nevyužité Relics (?)
<img width="924" alt="Screenshot 2020-05-02 at 13 37 36" src="https://user-images.githubusercontent.com/64065488/80863117-3fa68d80-8c7a-11ea-8db0-bba354d310ef.png">

**Comment by faire2** [comment]
Je to tak, dobry postreh.

**Comment by faire2** [comment]
Opraveno.
