### ISSUE TITLE
Nefunguje Tent

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#66]
a to mám pocit, že v minulé verzi fungoval, hm...

Zahrál jsem tent ale kliknutí na mou lokalitu nic nedělá
<img width="1119" alt="Screenshot 2020-05-02 at 16 14 33" src="https://user-images.githubusercontent.com/64065488/80866652-1f81c900-8c90-11ea-9c4b-931a797ef932.png">

**Comment by ElwenCGE** [comment]
Stejně tak nefunguje Golden Mask (podobný efekt)

<img width="1407" alt="Screenshot 2020-05-02 at 16 17 42" src="https://user-images.githubusercontent.com/64065488/80866706-78e9f800-8c90-11ea-9640-1c0a194a61f7.png">

**Comment by faire2** [comment]
Jo, rozbito pri uprave balonu, opraveno.
