### ISSUE TITLE
Nefunguje Portal Stone - tentokrát nelze odstranit panáčka

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#67]
<img width="1348" alt="Screenshot 2020-05-02 at 16 20 53" src="https://user-images.githubusercontent.com/64065488/80866789-f877c700-8c90-11ea-892e-d25e8d82377e.png">

**Comment by faire2** [comment]
Kod mi prijde v poradku, ve stejne lokaci nejsem schopny reprodukce.
