### ISSUE TITLE
V druhém kole nelze zahrát Bane Banisher

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#68]
Nejsem si jistý proč, v prvním kole šel, nevím jestli se to celé nějak nezaseklo (i díky množství karet) ..ještě to prozkoumám

<img width="793" alt="Screenshot 2020-05-02 at 16 26 07" src="https://user-images.githubusercontent.com/64065488/80866947-c4e96c80-8c91-11ea-8dc8-77bc776944fd.png">

**Comment by ElwenCGE** [comment]
v další hře jsem už bane bannisher zvládl zahrát v 1. i 3. kole, tak nevím

**Comment by faire2** [comment]
Zkoušel jsem, ještě jsem ho upravil, aby hráč dostal resource až po zničení karty. IMHO v pořádku.
