### ISSUE TITLE
Po zahrání Fishing rod (Compass?) se trvale rozšíří nabídka karet o jednu kartu

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#71]
<img width="974" alt="Screenshot 2020-05-03 at 09 36 26" src="https://user-images.githubusercontent.com/64065488/80908632-adf25b00-8d21-11ea-8443-679ace6993e2.png">

Koupil jsem tu extra nejvíc vpravo kartu

**Comment by ElwenCGE** [comment]
repro potvrzeno u kompasu, tam se dokonce nabídka artefaktů rozšíří doprava a přeteče na pravou stranu hole (na místo itemu?) a pokud si koupím ten artefakt, tak to crashne appku

**Comment by faire2** [comment]
Opraveno, dělo se to při vybrání krajní karty (nově odhalené).
