### ISSUE TITLE
Po umístění Discovery tokenu (relic) jsem nedostal zlaťák

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#72]
<img width="802" alt="Screenshot 2020-05-03 at 09 44 05" src="https://user-images.githubusercontent.com/64065488/80908742-c2832300-8d22-11ea-918c-96d27a3bd25a.png">
Levá spodní pozice - umístil jsem a mám stále 0 zlato

**Comment by faire2** [comment]
Opraveno.
