### ISSUE TITLE
Porazil jsem Guardiana (Dock action) ale nevrátila se mi zpět karta, kterou Guardian zamknul

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#74]
<img width="1396" alt="Screenshot 2020-05-03 at 18 13 43" src="https://user-images.githubusercontent.com/64065488/80919377-eddd3080-8d69-11ea-8f36-a0285cff2354.png">

**Comment by ElwenCGE** [comment]
Zničil jsem Guardiana přes lokalitu (Naga) a taky mi nevrátil 2 zamčené karty

**Comment by faire2** [comment]
Opraveno. Dve hodiny prace :) Diky, ze jsi tam napsal o tom zpusobu zniceni.
