### ISSUE TITLE
Nelze zničit karta v discard pile

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#75]
zahrál jsem Whip
získal přes něj Cursed Treasure
ten mi dal 4 coiny a Fear do discard pile
zahrál jsem Machete (EE a destroy kartu)
snažím se, ale nejde kliknout na Fear v discard pile (jen mi s každým klikem problikávají a promíchavájí karty v Draw decku)

**Comment by faire2** [comment]
Opraveno. Chyba byla ve Fearu ziskanem skrze efekt (nemel definovany stav Discard, takze nesel znicit, protoze to lze jen u karet s definovanymi stavy).
