### ISSUE TITLE
Nejde dotáhnout karta z Discardu pomocí Ring of Light

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#76]
Asi tam máš teď problém, že se nedá kliknout na kartu v discard pile viz #75 
Zahrál jsem Ring of Light a nejsem schopný si vytáhnout kartu z discardu

**Comment by ElwenCGE** [comment]
Díky tomuto bugu se patrně i nějak zvláštně zduplikovaly některé karty (plane, transmutation..):
<img width="1415" alt="Screenshot 2020-05-03 at 20 40 27" src="https://user-images.githubusercontent.com/64065488/80922588-6cdc6400-8d7e-11ea-85e1-7d5e44c72078.png">

**Comment by faire2** [comment]
Stejny problem, karta nemela definovany stav (z jineho duvodu, ale projevilo se to stejne - odstranil jsem pricinu, snad by to uz nemelo zlobit).
