### ISSUE TITLE
Update Expedition Goals

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#78]
[ExpeditionNand3.pdf](https://github.com/faire2/loreHunters/files/4571444/ExpeditionNand3.pdf)

Stačí ti to takto? Kdybys to chtěl v jiném formátu, napiš.

**Comment by faire2** [comment]
@ElwenCGE K tomuhle bych jeste potreboval pozadi s mistem na body.

**Comment by faire2** [comment]
Hidden gems: nema to byt each item?

**Comment by faire2** [comment]
Cartographer nema maximum.

**Comment by ElwenCGE** [comment]
Hidden gems, ano - each item
Cartographer - dává jen 1VP za Relic, takže nemusí mít maximum (doufám :))

**Comment by faire2** [comment]
![image](https://user-images.githubusercontent.com/45813901/80925377-9356cb00-8d8f-11ea-9bed-0bb12ed5e493.png)
 
Je tam chyba v textu.

**Comment by faire2** [comment]
Neni holy grail trochu moc silne? Jak casto se stane, ze nedosahnes pokladu?

**Comment by ElwenCGE** [comment]
Máš pravdu, má to být 

for each (D) that you own.
(btw jsi na Slacku? :) )

**Comment by faire2** [comment]
Jj, ale jeste jsem se tam nedival.

Animal person - navrhuju zmenit na animal tamer / handler / whisperer

**Comment by faire2** [comment]
Assistant that you own - to neni stastna formulace :) That you gained?

**Comment by ElwenCGE** [comment]
sure, to jsou detaily :)

**Comment by ElwenCGE** [comment]
když už chatujeme tady, ptal jsem se jestli pushneš nějaký nový build. Vidím, že jsi spravil pár bugů, tak by bylo fajn hrát na něčem čerstvém :)

**Comment by faire2** [comment]
Mmnt!
