### ISSUE TITLE
Multiplayer bug - goal cards

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#84]
Když si jeden hráč vybere startovní Goal kartu a stihne odehrát i svůj tah dřív, než se druhý rozhodne, kterou Goal kartu si vybere - tak se tomu pomalejšímu Goal karty ze kterých si vybírá změní na jiné :)

**Comment by faire2** [comment]
Prozatim nastaveno tak, ze si hraci vybiraji kartu az behem sveho tahu. Muzes napsat rozdani exp. karet na zacatku vsem jako novy enhancement, jestli chces.
