### ISSUE TITLE
Nelze postoupit na Legendě i když na to mám resources

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#93]
Mám Jewel a Tablet, ale kliknutí na horní druhý sloupec nic nedělá, když kliknu na třetí sloupec, kde je stejná cena, tak se posun provede.

<img width="672" alt="Screenshot 2020-05-08 at 15 48 16" src="https://user-images.githubusercontent.com/64065488/81411971-66b20300-9143-11ea-8b56-d779bde592a3.png">

**Comment by faire2** [comment]
Opraveno, souviselo s 3. tokenem.
