### ISSUE TITLE
Items update (8 May)

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#94]
[ItemsNand15.pdf](https://github.com/faire2/loreHunters/files/4599480/ItemsNand15.pdf)

**Comment by faire2** [comment]
Navrh: namisto bow and arrow mit nejakou pusku s dalekohledem, IMHO by to lepe vysvetlovalo explory

**Comment by faire2** [comment]
Pocket watch bylo velké zlo...
