### ISSUE TITLE
Lze zahrát karta z Draw decku

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#97]
Některé karty v Draw decku mají status in Hand a skutečně jdou zahrát
<img width="697" alt="Screenshot 2020-05-09 at 15 40 58" src="https://user-images.githubusercontent.com/64065488/81475373-0d61d680-920c-11ea-8bad-dcb0d01208fa.png">

**Comment by ElwenCGE** [comment]
v té chvíli karty v ruce, zdá se že je to opět problém, pokud je v draw decku i v play area stejný typ karty:
<img width="841" alt="Screenshot 2020-05-09 at 15 45 53" src="https://user-images.githubusercontent.com/64065488/81475397-36826700-920c-11ea-8c3d-40bf245a472b.png">

**Comment by faire2** [comment]
Udělal jsem úpravu procky. která přidává karty do discardu. Budu to hlídat.
