### ISSUE TITLE
Nemožnost ukončit kolo

### ISSUE THREAD

**Issue by ElwenCGE** [faire2/loreHunters#99]
Klikám na end turn a nic se neděje. Poslední akce bylo zahrání zlaťáku z ruky
<img width="1434" alt="Screenshot 2020-05-09 at 21 45 25" src="https://user-images.githubusercontent.com/64065488/81483456-92fe7a00-923e-11ea-9c36-6017d56f9bb2.png">

**Comment by ElwenCGE** [comment]
Hm, tak crashnula appka, takže to bylo tím.

**Comment by ElwenCGE** [comment]
Zatím se mi bohužel nepodařilo dohrát hru do konce, tak snad zítra to klapne.

**Comment by faire2** [comment]
Já jsem dneska dohrál asi 4x, ani jednou to nespadlo. Divné.

**Comment by ElwenCGE** [comment]
Já to nemyslel tak, že by mi to pokaždé spadlo, tak zlé to není :-)) Ale vždy jsem narazil na nějaký bug, který mi to znemožnil hrát kompetetivně na body, tak jsem začínal znovu. Chci totiž začít zkoušet proti sobě různé strategie.

**Comment by ElwenCGE** [comment]
hm, tak ta nemožnost ukončit tah se mi stala znova. Tentokrát jsem neklikal kolem, díky tomu to snad necrashlo a byl jsem schopný začít novou hru

**Comment by ElwenCGE** [comment]
Tak ještě do třetice se mi to stalo, tentokrát jsem si trochu poklikal a appka crashla, takže dneska dotestováno. Dobrou :)
